@ECHO OFF
ECHO Loading DB ...
docker run -d -p:3306:3306 --name mySQLDB -t junkbarwellca/robbarwell:simmanagerdb
ECHO Loading Sim Manager ...
docker run -d -p80:80 -v c:/SimManager/Settings/cfg_simmanager.js:/var/www/html/js/config/cfg_simmanager.js --name SimManager -t junkbarwellca/robbarwell:simmanager
ECHO Loading Sim Visualizer ...
docker run -d -p81:80 -v c:/SimManager/Settings/cfg_simvisualizer.js:/var/www/html/js/config/cfg_simvisualizer.js --name SimVisualizer -t junkbarwellca/robbarwell:simvisualizer
ECHO Waiting for DB ...
TIMEOUT 30
ECHO Loading Manage Experiment ...
docker run -v c:/SimManager/Settings/PRODmanageexperiment.properties:/microservice/config/application.properties -v c:/SimManager/Shared/experiments:/data --name ManageExperiment -d -p8091:8080 junkbarwellca/robbarwell:manageexperiment
ECHO Loading Run Experiment ...
docker run -v c:/SimManager/Settings/PRODrunexperiment.properties:/microservice/config/application.properties -v c:/SimManager/Shared:/common -v c:/SimManager/Simulators/Cadmium:/cadmium -v c:/SimManager/Scripts/Cadmium:/scripts/cadmium --name RunExperiment -d -p8092:8080 junkbarwellca/robbarwell:runexperiment
ECHO Loading View Experiment ...
docker run -v c:/SimManager/Settings/PRODviewexperiment.properties:/microservice/config/application.properties -v c:/SimManager/Shared/experiments:/data --name ViewExperiment -d -p8093:8080 junkbarwellca/robbarwell:viewexperiment
ECHO Completed Sim Manager Installation