CC=g++
CFLAGS=-std=c++17

INCLUDECADMIUM=-I [(${myEnvVars.getProperty("cadmium.include_base")})]
INCLUDEDESTIMES=-I [(${myEnvVars.getProperty("cadmium.include_time")})]
INCLUDEATOMICS=-I [(${myEnvVars.getProperty("cadmium.include_atomics")})]
INCLUDES=[(${myEnvVars.getProperty("cadmium.include_includes")})]

# === COUPLED ===
sim.o: sim.cpp
	$(CC) -g -c $(CFLAGS) $(INCLUDECADMIUM) $(INCLUDEDESTIMES) $(INCLUDEATOMICS) sim.cpp -o sim.o

# === DEPLOY ===
sim: sim.o
	$(CC) -g -o sim sim.o [# th:each="myObject : ${myModel.getMyTopModel().getObjects()}"]$(INCLUDES)[(${myObject})].o [/]